services:
  postgres:
    restart: unless-stopped
    image: postgres:18
    env_file:
      - .env.postgres
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - authentication-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authentication_management"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  authentication-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: authentication-service
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - authentication-network
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - jwt_secret
      - jwt_refresh_secret
      - postgres_password


networks:
 authentication-network:

volumes:
  postgres-data:

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt

  jwt_refresh_secret:
    file: ./secrets/jwt_refresh_secret.txt

  postgres_password:
    file: ./secrets/postgres_password.txt
