CREATE TABLE IF NOT EXISTS users
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role varchar(50) NOT NULL DEFAULT 'USER',

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT check_users_role
        CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean NOT NULL DEFAULT false,

    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT refresh_tokens_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_active_user
    ON refresh_tokens (user_id)
    WHERE revoked = false;

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_tokens_token
    ON refresh_tokens (token);
